services:
  mongodb-server:
    image: mongo
    restart: always
    ports:
      - 27107:27107
    # volumes:
    #   - /var/lib/mongodb_server:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-api-app:
    build: .
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app